import Header from "../components/Header";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdvertWork from "@/components/AdvertWork";
import AdvertisePage from "@/components/AdvertisePage";
import Explore from "@/components/Explore";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
// import Logo from "../../images/Logo.png";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Advertorial Hub",
  description: "Generated by create next app",
};
const Layout = ({ children }) => {
  useEffect(() => {
    window.scrollTo(0, 0); // Reset scroll position
  }, []); }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          <img src="/images/Logo.png" alt="Logo" />
          Advertorial Hub
        </title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Header />
        </header>
        <main>
          <Hero />
          <AdvertisePage />
          <AdvertWork />
         
          <Explore/>
        </main>{" "}
        {/* This renders the page content */}
        <footer>
        <Footer/>
        </footer>
      </body>
    </html>
  );
}
