import Header from "../components/Header";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdvertWork from "@/components/AdvertWork";
import AdvertisePage from "@/components/AdvertisePage";
import Explore from "@/components/Explore";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import { IBM_Plex_Sans, Source_Serif_4 } from "next/font/google";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-ibm-plex-sans",
  display: "swap",
});

const sourceSerifPro = Source_Serif_4({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "600"],
  variable: "--font-source-serif-pro",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Advertorial Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${ibmPlexSans.variable} ${sourceSerifPro.variable}`}
    >
      <head>
        <title>Advertorial Hub</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Header />
        </header>
        <main>
          <Hero />
          <AdvertisePage />
          <AdvertWork />

          <Explore />
        </main>{" "}
        {/* This renders the page content */}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
